### ISSUE TITLE
Is there a way to protect your self from releasing a release marked as Pre-Release?

### ISSUE THREAD

**Issue by oppknox** [dawidd6/action-download-artifact#105]
I thought GitHub would do this for me, but apparently that isnt the case. Would you be able to add a flag to protect against it?

    - name: Download latest Blazor artifact
      if: ${{ null == github.event.inputs.runnumber  }}   
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ env.Release_Action_Workflow }} 
        workflow_conclusion: success
        name: Test.Blazor.Wasm
        path: ./web

**Comment by dawidd6** [comment]
I don't understand the issue

**Comment by oppknox** [comment]
If I create a main release, then create another release in a different branch and check the box "Pre-Release", but using the script above to deploy the latest successful release it'll grab the Pre-Release in a branch that I didnt intend to release. I'm looking for either a safety to ensure I can only deploy the latest Main branch or a safety to ensure I never deploy anything marked as Pre-Release

![image](https://user-images.githubusercontent.com/34199047/133955787-2c32d00c-f377-4669-87c5-f5c6dc89ed42.png)

**Comment by oppknox** [comment]
Well actually I just looked again... looks like I can lock a branch. I thought I tried this before and ran into an issue. I'll try it again, if that works a block on pre-release would be less interesting.

 branch: master
    # Optional, defaults to all types
