### ISSUE TITLE
workflow_conclusion neutral?

### ISSUE THREAD

**Issue by chingc** [dawidd6/action-download-artifact#106]
Sorry, I'm not sure where to ask this, but what does it mean to set `workflow_conclusion` to `neutral`?  Does this mean it will search for workflows regardless of success or failure?  Or is `neutral` its own distinct conclusion?

I tried to look for an explanation in github docs but all I found was this which also didn't clarify: https://docs.github.com/en/rest/reference/checks#create-a-check-run

Thanks in advance.

**Comment by dawidd6** [comment]
![68747470733a2f2f646f63732e6769746875622e636f6d2f6173736574732f696d616765732f636865636b5f7375697465732e706e67](https://user-images.githubusercontent.com/9713907/134388267-b00c2241-0802-4fac-bd31-4f94ce698569.png)

If I understand this correctly `neutral` conclusion means the check run completed with warnings.

**Comment by chingc** [comment]
Hmm... I'm still not completely sure but at least the image shows that `neutral` is definitely its own distinct status.  Not `success || failure` which is what I initially thought.  Thanks.
