### ISSUE TITLE
Allow for option to not fail on no artifacts found

### ISSUE THREAD

**Issue by Matenko** [dawidd6/action-download-artifact#110]
The workflow that this runs on for us may or may not have any artifacts to download due to the previous workflow being a conditional artifact upload. Would it be possible to add an option to allow for the failure and is just set to false by default? We don't want to fail our workflow if no artifacts are found as we're already doing appropriate checks downstream for the expected unzipped directory.

**Comment by dawidd6** [comment]
See https://github.com/dawidd6/action-download-artifact/issues/33

**Comment by Matenko** [comment]
Aha. Perfect. Thank you!
