### ISSUE TITLE
Artifact not found, but found on rerun

### ISSUE THREAD

**Issue by sangeetadhingra** [dawidd6/action-download-artifact#118]
When running a workflow with a job to download an artifact from another workflow (upon the prior workflow completion, not necessarily success) the artifact cannot be found half the time and the workflow fails, but as soon as the workflow is reran the artifact is found. I added a sleep 15s job right before but the artifact still is not found a number of times, until manually reran.

**Comment by dawidd6** [comment]
This is most likely GitHub's fault. Action does not do much besides calling GitHub API.
