### ISSUE TITLE
Failed to generate URL to download artifact

### ISSUE THREAD

**Issue by josejulio** [dawidd6/action-download-artifact#120]
This is an error I started to see today - I'm unsure if something changed in the API

See: https://github.com/RedHatInsights/policies-ui-frontend/runs/4238960045?check_suite_focus=true#step:6:18

Is there any way to provide more details?

**Comment by dawidd6** [comment]
Hard to tell, I'm not aware of any GitHub API change recently. Might just be some temporary issue.

**Comment by josejulio** [comment]
I'll try tomorrow. 
Do you think it would be possible to have a verbose flag to print out the exception?

**Comment by dawidd6** [comment]
It already prints the exception message. Not sure what else you would want to see.

**Comment by josejulio** [comment]
I'm still having this issue, upon some reading it looks like the `secrets.GITHUB_TOKEN`  [permissions are limited to the repository that contains your workflow](https://docs.github.com/es/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).

I don't think it was true before as it was working well to download files from other repository.
