### ISSUE TITLE
Option to not fail but output status

### ISSUE THREAD

**Issue by prince-chrismc** [dawidd6/action-download-artifact#124]
👋 Love this action, but there's a slight improvement i'd love to make where failing the job was optional.

My use case is fairly simple
1. run lint
    - if staged is dirty then upload artifact
2. on workflow_run completed
    - if artifacts commit changes _else success_

Sadly the only limitation I've encountered is the success report.

Would it be possible to add an input/output to the action to avoid this line?

https://github.com/dawidd6/action-download-artifact/blob/09385b76de790122f4da9c82b17bccf858b9557c/main.js#L127

**Comment by dawidd6** [comment]
Did you consider using GitHub Actions mechanisms to achieve what you want?

https://docs.github.com/en/actions/learn-github-actions/expressions#success
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

**Comment by prince-chrismc** [comment]
Thank you! I did not know continue on error 🤯 

https://github.com/prince-chrismc/label-merge-conflicts-action/actions/runs/1564839124/workflow
