### ISSUE TITLE
Downloading from the current workflow

### ISSUE THREAD

**Issue by jareware** [dawidd6/action-download-artifact#125]
Thanks for this action, super helpful!

Is there come combination of options that would allow you to download artifacts from a past step in the same workflow? I know I can already use `actions/download-artifact@v2` for that, but we need to do one or the other depending on what kind of a deploy we're running, and would be lovely to simply use `dawidd6/action-download-artifact` for both cases.

**Comment by dawidd6** [comment]
No way to do that currently. Would accept PRs to change it.

**Comment by jareware** [comment]
Took a quick look and indeed the build artifacts aren't made available until the whole workflow has finished (as opposed to just the job/step that produces them), so no low-hanging fruits to be had here.

Thanks anyway!
