### ISSUE TITLE
octokit breaking changes

### ISSUE THREAD

**Issue by hwellmann** [dawidd6/action-download-artifact#126]
The latest version of this action depends on `@actions/github@5.0.0`. In this version, after creating a client like

```
const client = github.getOctokit(token)
```

the REST APIs should be called via`client.rest`, e.g.

```
client.rest.actions.listWorkflowRuns(...)
```
instead of 

```
client.actions.listWorkflowRuns(...)
```

So it's bit of a surprise that v2.16.0 works in production. I do get an exception when stepping through the code locally, because `client.actions` is undefined.

**Comment by dawidd6** [comment]
Thanks for heads up. Didn't know about it. A PR fixing those deprecations would be nice 😄.

**Comment by hwellmann** [comment]
Ok, found it: The `node_modules` folder doesn't match `package.json` and still contains `@actions/github@4.0.0`.

In my local clone, I ran `npm install` first of all, not noticing that `node_modules`are part of the repo.

Wouldn't it be better to remove `node_modules` completely and use the recommended `ncc` build`?

See https://github.com/actions/javascript-action

**Comment by dawidd6** [comment]
To be honest I favor `node_modules` approach, it's easier to maintain and debug. This drift must have been caused by merging some Dependabot PR. Dependabot itself does not update `node_modules` nor does it run any other command like `npm run package` AFAIK.

**Comment by godefroi** [comment]
So the most recent version is broken; how are we to handle this?
