### ISSUE TITLE
Disable inflation

### ISSUE THREAD

**Issue by curtisma** [dawidd6/action-download-artifact#129]
When zip file artifacts are downloaded they are unzipped or "inflated".  There should be an option to disable this feature so the zip files are just downloaded without being unzipped.

Specifically I need to download a build artifact and then reupload it, with it still zipped.

**Comment by dawidd6** [comment]
Please submit a PR for that.

**Comment by dawidd6** [comment]
Implemented.

**Comment by curtisma** [comment]
> Implemented.

Awesome!  Thanks!
