### ISSUE TITLE
Inflated filename has asterisks in it

### ISSUE THREAD

**Issue by janissimsons** [dawidd6/action-download-artifact#135]
Hi,

Why are there asterisks in my filename after having downloaded it?

![image](https://user-images.githubusercontent.com/6424248/155189863-765dddb1-1733-4f49-a961-c912bf751b84.png)

The correct name should be: "REL-26_SHA-76e86d7_2022-02-22_17-43-12.tar.gz"

**Comment by dawidd6** [comment]
Dunno. Without some more informations, what can I do?

**Comment by ATPAustinPeng** [comment]
Where does this download even download to @dawidd6

**Comment by dawidd6** [comment]
I don't understand the question.

**Comment by dawidd6** [comment]
Issue is stale, closing.
