### ISSUE TITLE
Error: no matching workflow run found

### ISSUE THREAD

**Issue by vitalyk-multinarity** [dawidd6/action-download-artifact#138]
I guess I'm missing something basic, but I couldn't not find it...
I'm trying the most basic configuration. Yes, I provided "github_token:" from github secrets.
`Run dawidd6/action-download-artifact@v2
==> Workflow: myflow.yml
==> Repo: myorg/myrepo
==> Conclusion: completed

Error: no matching workflow run found`

My flow runs about 1.5-3 minutes, so I think it interacts with Github. Is there a way to add a debug output?

TIA, Vitaly

**Comment by dawidd6** [comment]
Show the workflows, can't say anything without seeing what are you trying to achieve.

**Comment by vitalyk-multinarity** [comment]
> Show the workflows, can't say anything without seeing what are you trying to achieve.

Thank you! These are private repos A and B, and I'd like to use artefact from A in the B.
My B flow is:

`        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          workflow: A-flow.yml
          workflow_conclusion: 'completed'
          repo: 'myorg/a-repo'
          check_artifacts:  true
          search_artifacts: false`
          
          Thank you, Vitaly

**Comment by dawidd6** [comment]
Delete search_artifacts line completely and try again.

**Comment by vitalyk-multinarity** [comment]
Dawid, it works now!
First of all, many thanks for your plugin and prompt support!
Two points:
1) This behavior seems me a bug
2) If possible, I'd like to see easier way to identify downloaded
artefacts. For now I see in the log only:

==> RunID: 1944802043
==> Artifact: 179509382

and I'm not sure how to understand these details. I guess that RunID is the
internal Github run id, and I see no easy way to link it to the workflow
run number or commit hash.

Thank you again,
Vitaly
