### ISSUE TITLE
second unpack would be nice

### ISSUE THREAD

**Issue by lovettchris** [dawidd6/action-download-artifact#140]
Sometimes the uploaded artifact is itself a .zip file or a .tar.gz or .tar.zst file and it would be cool if you added an option to do a second unpack/unzip on that inner archive file.  Perhaps an "secondary_unpack: location" option or something.  For example `https://github.com/leanprover/lean4/releases/tag/v4.0.0-m3` release contains:
```
lean-4.0.0-darwin.tar.zst   107.99 MiB
lean-4.0.0-darwin.zip       150.59 MiB
lean-4.0.0-linux.tar.zst    111.84 MiB
lean-4.0.0-linux.zip        209.51 MiB
lean-4.0.0-windows.tar.zst  116.01 MiB
lean-4.0.0-windows.zip      162.28 MiB
```
And I need to use these in another repo to run tests, and would be nice if I didn't have to write a bunch of shell scripts to unpack these files.

**Comment by dawidd6** [comment]
Would be great if you provided a PR for the feature you are describing.

**Comment by dawidd6** [comment]
No further interest, closing.
