### ISSUE TITLE
[Feature Request] Allow for retrieval from the entirety of the repo and not just a workflow

### ISSUE THREAD

**Issue by daylamtayari** [dawidd6/action-download-artifact#152]
A really useful feature would be to allow for the search and retrieval of artifacts throughout the entirety of the repository and not a single workflow.

This would allow for the artifact of a build of a specific release or commit being able to be easily reused in other jobs without having to know which workflow was responsible for the creation of the artifact.

As aforementioned, I will submit a PR introducing this feature.

**Comment by dawidd6** [comment]
Are you still working on that?

**Comment by daylamtayari** [comment]
Yes sorry, got busy and forgot. Will work on it as soon as I have the time.

**Comment by dawidd6** [comment]
I think this got implemented in meanwhile
