### ISSUE TITLE
Deprecation warning and failure

### ISSUE THREAD

**Issue by GaryHughes** [dawidd6/action-download-artifact#16]
Hi, I get the following when trying to use this action.

[@octokit/paginate-rest] "response.data.workflow_runs" is deprecated for "GET /repos/GaryHughes/Exchange/actions/workflows/part_1_cpp.yml/runs". Get the results directly from "response.data"
10
##[error]Cannot read property 'id' of undefined

**Comment by dawidd6** [comment]
You have to specify one of the `commit` or `pr` inputs.

**Comment by GaryHughes** [comment]
Thanks, working now. Is it possible to make the API work without this? It introduces a bit of maintenance I'd like to avoid if possible.

**Comment by dawidd6** [comment]
https://github.com/dawidd6/action-download-artifact/issues/12 might be relevant.

**Comment by GaryHughes** [comment]
Thanks I'll see how I go and if I find the time I'll try and contribute that change.
