### ISSUE TITLE
'path' key with 'skip_unpack'

### ISSUE THREAD

**Issue by iTrooz** [dawidd6/action-download-artifact#168]
When `skip_unpack` is enabled, `path` seems not to do anything (the artifacts are still downloaded to the current directory)

I'm willing to submit a PR for this

**Comment by dawidd6** [comment]
Please do

**Comment by iTrooz** [comment]
Done !
I have a question tho : 
In your code (main.js), I see that some keys are marked as required, but they're not inside action.yml, and indeed they're not required by Github Actions
Would you mind explaining this to me ?

**Comment by dawidd6** [comment]
Not required inputs in action.yml but required in main.js? That's because they have default values set, so you don't have to always specify them by yourself.
