### ISSUE TITLE
Unable to find 'in_progress' artifact from the calling workflow

### ISSUE THREAD

**Issue by PJ-AFI** [dawidd6/action-download-artifact#173]
Hey there. 

I have two Workflows:
- [A], which uploads an artifact and then, in a later job that needs the upload job, makes a workflow_call to...
- [B], which (attempts to) retrieve the artifact from the in_progress parent workflow

As well as workflow_call, Workflow [B] can also be triggered by workflow_dispatch (in which case it retrieves the artifact from a previous, successful parent workflow run, according to a provided run number).

I am sadly unable to re-use the dawidd6/action-download-artifact action for both scenarios :( ...
Changing `workflow_conclusion` seems to be working; but in the case of 'in_progress' scenario, it reports that although it *did* identify a suitable workflow, it was not able to find any artifacts associated with it.

My workaround is not very elegant; it is to re-upload the artifact in Workflow [B] if its the manual/ad-hoc scenario, using an identical name - which allows me to use the bog-standard actions/download-artifact@v3 in either scenario (to avoid forking the post-processing jobs, which are more or less identical).

Maybe I'm doing something wrong or have a misconception, but thought I'd share. :)

**Comment by dawidd6** [comment]
AFAIK workflow run needs to end to be able to get artifacts from it. That's how it works, I haven't looked into making it work with in progress workflow runs. Maybe there is a room for improvement here.

**Comment by flobernd** [comment]
@dawidd6 

I run into the same limitation. Maybe it's possible to implement a fallback to the default `download-artifact` action if `workflow_conclusion == in_progress` and none of `pr`, `branch`, `commit`, ... is set? This might as well reduce REST calls in this scenario but still allows usage of your advanced action in e.g. reusable workflows.

**Comment by dawidd6** [comment]
This looks sensible. I would review a PR implementing this.
