### ISSUE TITLE
There shouldn't be a default value for workflow_conclusion

### ISSUE THREAD

**Issue by coder-hugo** [dawidd6/action-download-artifact#176]
The code treats it already as an optional parameter but since the `action.yml` defines a default value there is no way to skip the workflow conclusion check.

**Comment by dawidd6** [comment]
You can set the input to an empty string.

**Comment by henrihs** [comment]
From a usability perspective, the default conclusion should be the empty string. It feels obvious that the conclusion isn't something you'd like to filter on if you don't pass it as an argument. This would be a breaking change though, maybe something to consider if introducing v3 at any point.

**Comment by dawidd6** [comment]
Documented. Closing...
