### ISSUE TITLE
Boolean inputs aren't handled as booleans

### ISSUE THREAD

**Issue by amezin** [dawidd6/action-download-artifact#179]
Currently, if you pass `false` to any of the "boolean" inputs, it will be treated as `true`. Because `getInput()` returns a string, and `Boolean("false")` evaluates to `true`.

Newer actions toolkit has `core.getBooleanInput()`. For it, https://github.com/dawidd6/action-download-artifact/pull/166 needs to be merged (with corresponding updates to the bundled `node_modules`).

**Comment by dawidd6** [comment]
Could you submit a PR for that? I agree current behavior isn't what we want.

**Comment by amezin** [comment]
I'm not using this action anymore (got rid of cross-workflow artifact passing). And, unfortunately, I don't have the time to fix things I'm not using. From the description, it should be obvious what to fix and how.
