### ISSUE TITLE
Respect "if_no_artifact_found value" for "Artifact has expired" error

### ISSUE THREAD

**Issue by koplo199** [dawidd6/action-download-artifact#210]
Hi,
It would be great if the action could use the behavior defined by `if_no_artifact_found` for the following error `Error: Artifact has expired`, which is happening when an artifact is too old to be downloaded. This is something that could be expected, and it would be great to be able to just warn for it using `if_no_artifact_found: warn`

**Comment by koplo199** [comment]
Fixed by #211 
Thanks @dawidd6 for accepting the PR!

**Comment by AndreiMihalciuc** [comment]
Hi @dawidd6 thanks a lot for such an amazing GH action! It is really useful in our pipeline. 
When can we expect a new release which contains this PR?

**Comment by dawidd6** [comment]
Released.

**Comment by AndreiMihalciuc** [comment]
ohh wow!!! The quickest response I ever seen 🚀 Huge thank you!!!
