### ISSUE TITLE
Node 12 deprecation

### ISSUE THREAD

**Issue by hannes** [dawidd6/action-download-artifact#215]
Hi, thanks for this action, works great. One minor issue, I'm getting a deprecation warning from GitHub:

`
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/upload-artifact@v2
`

**Comment by dawidd6** [comment]
This was already fixed many months ago.

https://github.com/dawidd6/action-download-artifact/commit/7dd9f94e74f79f5eb0eb3c7e92cdf9701cfe8001
