### ISSUE TITLE
Error when unzipping artifact

### ISSUE THREAD

**Issue by vlacrosaz** [dawidd6/action-download-artifact#217]
I got the following error when trying to unzip an artifact from an old job : 

```
==> Downloading: emb-ihm_lib_3685551390.zip (14.69 MB)
Error: Invalid or unsupported zip format. No END header found

```
It works perfectly when the artifact is found on the last job. The issue only happen when the artifact is found on an older job

Here are the options I have : 
```
workflow: main.yml
workflow_conclusion: success
name: "emb-ihm_lib_${{ github.event.inputs.release_builder_build_id }}"
search_artifacts: true
path: snapshot/
```

**Comment by dawidd6** [comment]
Too few info to say anything
