### ISSUE TITLE
Question: chmod persistence 

### ISSUE THREAD

**Issue by Dekken** [dawidd6/action-download-artifact#22]
it seems chmod persistence is a known issue as noted here:
https://github.com/actions/upload-artifact

```
Permission Loss
exclamation File permissions are not maintained during artifact upload exclamation For example, if you make a file executable using chmod and then upload that file, post-download the file is no longer guaranteed to be set as an executable.
```

could attempting a "chmod +x" be something that is done by this action perhaps?

**Comment by dawidd6** [comment]
Don't really know how would you like that to be done. If you can and want, submit a PR and we'll see

**Comment by Dekken** [comment]
Yeah I dunno either, might just be simplest to do it in the step before it's used
