### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by pascalnaber** [dawidd6/action-download-artifact#222]
When fetching an artifact we get the following error: Error: Resource not accessible by integration

What are we doing wrong?

The following permissions are configured:

permissions:
  id-token: write
  contents: read
  pull-requests: write

We have 2 workflows.
The first one adds an artifact on the creation of a PR:

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: ${{ inputs.terraform_directory }}/tfplan

The artifact is saved as expected with the name "tfplan"

And the second workflow fetches the artifact on the approval of a PR:

    - name: Download Plan
      id: download-plan
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.github_token }}
        workflow: plan.yml
        pr: ${{ inputs.pr_id }}
        name: tfplan
        path: ${{ inputs.terraform_directory }}

The output is: 

Run dawidd6/action-download-artifact@v2
  with:
    github_token: ***
    workflow: plan.yml
    pr: 3
    name: tfplan
    path: terraform
    workflow_conclusion: success
    repo: test/terraform-playground
    check_artifacts: false
    search_artifacts: false
    skip_unpack: false
    if_no_artifact_found: fail
  env:
    TERRAFORM_VERSION: 1.3.7
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
==> Repository: test/terraform-playground
==> Artifact name: tfplan
==> Local path: terraform
==> Workflow name: plan.yml
==> Workflow conclusion: success
==> PR: 3
==> Commit: 70d40ceb6b8347c1605c34abe71db49f5b4aa2cd
Error: Resource not accessible by integration

**Comment by pascalnaber** [comment]
We found the reason. 
Also read permission is needed on actions

permissions:
  id-token: write
  contents: read 
  pull-requests: write  
  actions: read

**Comment by jonsoku2** [comment]
```
permissions:
id-token: write
contents: read
pull-requests: write
actions: read
```

oh my god...thank you !! it was very helpful to me

**Comment by deviantintegral** [comment]
We were able to fix this with the following more restrictive permissions in the [workflow YAML](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token):

```
permissions:
  contents: read
  pull-requests: read
  actions: read
```
