### ISSUE TITLE
Download artifact from specific run

### ISSUE THREAD

**Issue by mortenlj** [dawidd6/action-download-artifact#23]
This looks very close to what I need. I have a workflow that saves an artifact, and then it makes a comment on the PR with details and the Run ID. My plan was to use the Run ID in a second workflow to get hold of the artifact and download it, but that turned out to be a bit too complicated at the moment.

Would it be possible to support supplying a run id to this action?

**Comment by dawidd6** [comment]
Care to submit a PR for that?

**Comment by mortenlj** [comment]
My JavaScript isn't all that great, but I can give it a go.
