### ISSUE TITLE
Upcoming GHA deprecations

### ISSUE THREAD

**Issue by DMRobertson** [dawidd6/action-download-artifact#233]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ announced:

> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

We've seen warnings about this in Synapse (e.g. [here](https://github.com/matrix-org/synapse/actions/runs/4607161929)). Would it be possible to update this action to avoid this? The blog claims that

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

so hopefully this should be sorted by a dependency update. (I'm not familiar with the javascript ecosystem, but I can give this a go if you'd be willing to accept the PR.)

**Comment by dawidd6** [comment]
Those warnings do not seem to come from this Action? Looking at the workflow run's logs you've provided.
