### ISSUE TITLE
search_artifacts: true

### ISSUE THREAD

**Issue by mattkoch-bb** [dawidd6/action-download-artifact#235]
Hi, thanks for this action. I was looking through the documentation, what exactly does `search_artifacts: true` do? I am trying to find the "latest" build artifact produced by another workflow.

**Comment by dawidd6** [comment]
https://github.com/dawidd6/action-download-artifact/blob/246dbf436b23d7c49e21a7ab8204ca9ecd1fe615/main.js#L123-L143

Searches for latest workflow run that produced an artifact, cause you can have workflow runs that did not produce an artifact and the Action would fail.
