### ISSUE TITLE
Error: Invalid response body while trying to fetch

### ISSUE THREAD

**Issue by SKuhlmanns** [dawidd6/action-download-artifact#238]
Can not download artifacts after action-download-artifact@v2.26.0. 

      - name: Get Library R/T artifacts
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          github_token: ${{secrets.REPO_RO_SECRET}}
          workflow: ${{env.WORKFLOW}}
          workflow_conclusion: success
          branch: ${{env.BRANCH_NAME}}
          name: libraries-linux-rt
          #name_is_regexp: false
          path: package
          repo: ${{env.LIB_REPO}}

Run dawidd6/action-download-artifact@v2.27.0
==> Repository: ***
==> Artifact name: libraries-linux-rt
==> Local path: package
==> Workflow name: develop.yml
==> Workflow conclusion: success
==> Branch: develop
==> (found) Run ID: 4448410424
==> (found) Run date: 2023-03-17T14:15:18Z
==> Artifact: 603924313
==> Downloading: libraries-linux-rt.zip (14.26 MB)
Error: Invalid response body while trying to fetch https://pipelines.actions.githubusercontent.com/serviceHosts/36285e3c-aeda-4c6a-9d53-0a539b14ecee/_apis/pipelines/1/runs/222/signedartifactscontent?artifactName=libraries-linux-rt&urlExpires=2023-04-24T21%3A16%3A14.4895722Z&urlSigningMethod=HMACV2&urlSignature=dc9yhJI0tIwnxY0Pi%2BIQRTRc97BrEBBQjP%2BprDAPPds%3D: read ECONNRESET

**Comment by dawidd6** [comment]
Works in my CI tests. Could this be some intermittent GH issue?

**Comment by SKuhlmanns** [comment]
I am currently using dawidd6/action-download-artifact@v2, but I only use it to download a run id text file that is uploaded with the artifacts.  I then wrote a script to use the run id, the GitHub API and wget to download the other large artifacts.  The nice thing about wget is that it retries 20 times which seems to solve my problem.  My guess is that our IT, security or network group is interrupting the downloads.  I haven't tried the action to download my large files, since I implemented the script.  Our Amazon Linux runners never seemed to be a problem; however, our Windows runners are inside our Network and can be problematic.   You can close the ticket since I found the work-around.
