### ISSUE TITLE
Self-hosted GitHub Supported

### ISSUE THREAD

**Issue by mmerchant** [dawidd6/action-download-artifact#239]
Seems like the action doesn't support self-hosted GitHub as there's no way to pass a baseUrl to Octokit?

https://github.com/dawidd6/action-download-artifact/blob/master/main.js#L43

The Octokit API does seem to support it: https://octokit.github.io/rest.js/v19

Is my understanding correct?

*update* My understand was incorrect. Action works with self-hosted as well.

**Comment by dawidd6** [comment]
I've never used self-hosted GitHub, nor have I access to it. Can't help but maybe others could chime in.
