### ISSUE TITLE
Error: no downloadable artifacts found (expired)

### ISSUE THREAD

**Issue by ahmedmoselhi** [dawidd6/action-download-artifact#244]
Hi I'm trying to download an artifact from my work flow i'm getting this error:
```
Run dawidd6/action-download-artifact@v2.27.0
==> Repository: ahmedmoselhi/phoenicis
==> Artifact name: Ubuntu
==> Local path: ./
==> Workflow name: 50152278
==> Workflow conclusion: success
==> (found) Run ID: 4936607979
==> (found) Run date: 2023-05-10T11:47:36Z
==> Artifact: 689029903
==> Downloading: Ubuntu.zip ([14](https://github.com/ahmedmoselhi/phoenicis/actions/runs/5840732222/job/15840298094#step:2:15)1.11 MB)
Error: no downloadable artifacts found (expired)
```
my yaml file content:
```
  build-release:
    needs: [ubuntu-java-11]
    name: "Build Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Download all workflow run artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          name: Ubuntu
.....
```

**Comment by dawidd6** [comment]
> By default, GitHub stores build logs and artifacts for 90 days, and this retention period can be customized. 

https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

**Comment by ahmedmoselhi** [comment]
> > By default, GitHub stores build logs and artifacts for 90 days, and this retention period can be customized.
> 
> https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

I just have made this build today! the artifacts should be there
