### ISSUE TITLE
Error: no artifacts found

### ISSUE THREAD

**Issue by CCS2BAN** [dawidd6/action-download-artifact#254]
I am trying to download the plan file which is uploaded through another workflow. It's throwing error not found.
<img width="304" alt="image" src="https://github.com/dawidd6/action-download-artifact/assets/121168469/c84c2b35-c353-41b5-b455-1647932b24e3">

Could you guide what are mandatory we need to add?

**Comment by anishp264** [comment]
Also had the same issue, but fixed it.
Make sure to provide the following:

- github_token: ${{ secrets.GITHUB_TOKEN }}
- workflow: pullbuild.yml  (the name of the workflow that produces the artifact)

ex:
- name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: pullbuild.yml # Name of the workflow that produced the artifact          
          name: my-markdown-file # Name of the artifact to downloadg
          path: artifacts

**Comment by CCS2BAN** [comment]
Hello @anishp264 ,
It is working now
Thanks,
Sandeep
