### ISSUE TITLE
CodeQL scanning alerts

### ISSUE THREAD

**Issue by Dylan-Prins** [dawidd6/action-download-artifact#256]
Hi Dawidd6,

I have forked your repo and turned on Advanced security.
I get 2 high security risks:

![image](https://github.com/dawidd6/action-download-artifact/assets/8777848/8bd01862-71fb-4f57-a94b-69f1f6727906)
 and
![image](https://github.com/dawidd6/action-download-artifact/assets/8777848/eed751e6-c238-4e63-b2f1-3e62783341cc)

Is this something you want to have on your backlog?
If I could I would have made a pull request but my Javascript skills are below 0.

**Comment by dawidd6** [comment]
Is there any real risk for this project though?

**Comment by Dylan-Prins** [comment]
I dont know, because i have no Javascript skills.
But a lot of company wont know either and therefore not use the action. Is it not better to always mitigate such alerts?

**Comment by dawidd6** [comment]
I've enabled the code scanning and closed those alerts as "won't fix", because I think they are exaggerated in this particular project and places. Thanks for heads up anyway.
