### ISSUE TITLE
`GLIBC_2.28' not found

### ISSUE THREAD

**Issue by ramanid-kr** [dawidd6/action-download-artifact#261]
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/vsts-agent/actions-runner/externals/node20/bin/node)

**Comment by dawidd6** [comment]
https://github.com/actions/runner/issues/2906

Pin to `https://github.com/dawidd6/action-download-artifact/releases/tag/v2.28.0` if you have a self-hosted runner with older glibc.
