### ISSUE TITLE
`/lib64/libm.so.6: version 'GLIBC_2.27' not found` in my self-hosted runners (Amazon Linux 2)

### ISSUE THREAD

**Issue by kota65535** [dawidd6/action-download-artifact#262]
Hi @dawidd6. First of all, thanks for creating and maintaining this useful action.

We are using this action in our Amazon Linux 2 self-hosted runners. Recently, we've hit the following error message.

```
/opt/runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /opt/runner/externals/node20/bin/node)
/opt/runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/runner/externals/node20/bin/node)
```

This is because:

- The action runtime is changed from `node16` to `node20` in the latest release [v2.28.1](https://github.com/dawidd6/action-download-artifact/releases/tag/v2.28.1) by this commit https://github.com/dawidd6/action-download-artifact/commit/587cee61f534dd8254d0baad7d7c511335afca24
- Node.js v20.x requires glibc >= 2.28
- Amazon Linux 2 comes with glibc 2.26, so the action fails to run

It seems to be common to bump the major version if the action runtime is updated. For example:

- https://github.com/actions/checkout/releases/tag/v4.0.0
- https://github.com/actions/setup-go/releases/tag/v5.0.0

It would be helpful if you could change the latest release tag to v3.0.0 and v3, and revert the v2 tag to refer v2.28.0 again.

**Comment by kota65535** [comment]
Oh, sorry duplicated #261

**Comment by kota65535** [comment]
@dawidd6 Thank you for the super-quick response!

**Comment by softok2** [comment]
Hello,
I have the same problem but at this date July 3,2024. Everything was working smoothly until today. 
In my self-hosted runner I cannot upgrade node version I was using v3 tag, then switch to v2 without any improvement , so my question:
Is there any work around for sorting this issue? 
Thanks in advance

**Comment by Idan-Lazar** [comment]
> Hello, I have the same problem but at this date July 3,2024. Everything was working smoothly until today. In my self-hosted runner I cannot upgrade node version I was using v3 tag, then switch to v2 without any improvement , so my question: Is there any work around for sorting this issue? Thanks in advance

It happens to us too

**Comment by calopezf** [comment]
I have the same issue. Please let us know how can we fix.

**Comment by adi-yuu** [comment]
+1
Facing this issue since July4 2024, is there a workaround for this ?

**Comment by zhulinJulia24** [comment]
+1

**Comment by bohana** [comment]
+1, as of yesterday out self hosted runner was working fine.

**Comment by bing-scenius** [comment]
+1

**Comment by Idan-Lazar** [comment]
+1

**Comment by joyyjoel** [comment]
I had the same issue yesterday, my github runner is failing all of a sudden.

How do In resolve this?

**Comment by jprusakiewicz** [comment]
+1

**Comment by niQQe** [comment]
+1

**Comment by zhulinJulia24** [comment]
https://github.com/actions/checkout/issues/1809

**Comment by dawidd6** [comment]
Nothing changed here in last 3 weeks, so I'm not sure if you should spam here about your issue. GitHub forcefully updated node 16 to node 20, I see. Thanks @zhulinJulia24 for linking the relevant issue.

**Comment by jprusakiewicz** [comment]
There is workaround here:
https://github.com/actions/checkout/issues/1590#issuecomment-2207052044

**Comment by joyyjoel** [comment]
Guys, I found a workaround, use this link or the comment below:

 [[mmomtchev](https://github.com/mmomtchev)](https://github.com/actions/checkout/issues/1590#issuecomment-2207052044)

```
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
```

in my workflow and it worked for me.

**Comment by ItayVortex** [comment]
@joyyjoel worked for me

**Comment by Vasanthan-Ponnivalavan** [comment]
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
  This doesn't work for me, actually it passes during the checkout phase and the build fails due to timeout error after this command was ran, I tried to change versions from v:11.3-alpine to v:14 -alpine and changed gitcheckout from v3 to v4 and downgraded to v2 and v1 as well, these solution doesn't work for me

**Comment by dawidd6** [comment]
Please continue the discussion in relevant repository. Impacting change was made by GitHub, not by me. Thanks.
