### ISSUE TITLE
Avoid create folder when upzip artifact

### ISSUE THREAD

**Issue by daniel-tron** [dawidd6/action-download-artifact#263]
When download an artifact like example.zip, it will create a folder example, how can I avoid this? I want to use the path parameter to extract artifact to a **target folder already exist**, currently I need an additional command to do this.

**Comment by dawidd6** [comment]
Please provide some more details, like workflow file or link to repository...

**Comment by daniel-tron** [comment]
Can't reproduce now. probably caused by uncleaned self-hosted runner.
