### ISSUE TITLE
illegal operation on a directory

### ISSUE THREAD

**Issue by jpfeuffer** [dawidd6/action-download-artifact#3]
In a very simple setup I get:

`##[error]EISDIR: illegal operation on a directory, open '/home/runner/work/hello-github-actions/hello-github-actions/.git/logs/refs/remotes/'`

What am I doing wrong?

**Comment by jpfeuffer** [comment]
This is the full output:
```
Run dawidd6/action-download-artifact@v2.0.0
  with:
    github_token: ***
    workflow: bar.yml
    pr: 4
    name: foo
    path: /home/runner/work/hello-github-actions/hello-github-actions
==> PR: 4
==> Commit: 66bfb882405b255e43c3fa7c08d5252c553ce0b1
==> Run: 57820265
==> Artifact: 3045729
##[error]EISDIR: illegal operation on a directory, open '/home/runner/work/hello-github-actions/hello-github-actions/.git/logs/refs/remotes/'
```

**Comment by dawidd6** [comment]
I was able to reproduce the issue: https://github.com/dawidd6/action-download-artifact/runs/515963400?check_suite_focus=true

Will try to fix it soon.

**Comment by dawidd6** [comment]
Should be resolved in latest release: https://github.com/dawidd6/action-download-artifact/releases/tag/v2.1.0

Please test and let me know.

**Comment by jpfeuffer** [comment]
Great! Works. Thanks for the quick fix.
