### ISSUE TITLE
handling of download fails

### ISSUE THREAD

**Issue by tb102122** [dawidd6/action-download-artifact#31]
Dear dawidd6,

thanks for your work in the action.
It is really helpful.
One question is there a option to return a Boolean if the artifact was not available and therefore the download was not successful?
Thanks for your help.

Regards

**Comment by dawidd6** [comment]
If the artifact is not found, the Action will just error out with current implementation.

**Comment by tb102122** [comment]
something seems to be wrong when I use it. It does not fail.
![image](https://user-images.githubusercontent.com/62531735/95318043-b73faf00-08e1-11eb-973d-2a6c54b118ed.png)

**Comment by dawidd6** [comment]
Could you show the whole workflow file.

**Comment by dawidd6** [comment]
This could be a potential fix: https://github.com/dawidd6/action-download-artifact/pull/32

**Comment by tb102122** [comment]
Here are the related steps.

job_layers:
    needs: job_prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job_prepare.outputs.layer_matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: matrix name
        run: |
          echo $GITHUB_WORKSPACE
          echo ${{ matrix.path }}
      - uses: technote-space/get-diff-action@v3
        id: git_diff
        with:
          PREFIX_FILTER: ${{ matrix.prefix }}
          SUFFIX_FILTER: Dockerfile
      - name: LayerDockerBuild
        id: layerDocker
        if: steps.git_diff.outputs.diff
        run: |
          docker build.... 
      - name: Layer via Artifacts
        if: (steps.git_diff.outputs.diff == false)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: review.yml
          name: ${{ matrix.name }}
      - name: Layer via Docker
        if: steps.git_diff.outputs.diff
        id: layerD
        run: |
         .......   
      - name: Upload layer zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.zip

**Comment by tb102122** [comment]
thanks, I will give it a try.
for my case it would be even more helpful to assign a Boolean which can be used in the following steps. 
Than I would be able to have an if with OR for the step

- name: Layer via Docker
if: steps.git_diff.outputs.diff
id: layerD
run: |
.......

Do you see that as a useful option for your action?

Cheers Tobias

**Comment by dawidd6** [comment]
The Action should now error out if no artifacts are found.
