### ISSUE TITLE
Include warning if artifacts not found

### ISSUE THREAD

**Issue by tb102122** [dawidd6/action-download-artifact#33]
Hey dawidd6,

would it be possible to change the artifact not found to a warning and create a boolean variable as output.
In that case we can continue with other steps in the workflow e.g. building the artifacts again from the actual sources.

Cheers

**Comment by tb102122** [comment]
I add the code changes based on my understanding in the PR.
https://github.com/dawidd6/action-download-artifact/pull/34
I am not an expert in JS so please revise it if it is not correct.

**Comment by dawidd6** [comment]
Why not just use `if: failure()` in workflow file?

**Comment by tb102122** [comment]
I tried that but for some reason it does not work.
Any idea why it is not working?

      - name: Layer via Artifacts
        if: (steps.git_diff.outputs.diff == false)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: review.yml
          name: ${{ matrix.name }}
      - name: Layer via Docker
        if: steps.git_diff.outputs.diff && ${{ failure() }}
        id: layerD
        run: |

thats the result afterwards of the steps inside of the matrix

![image](https://user-images.githubusercontent.com/62531735/97513097-66524080-19df-11eb-90d0-d2e5f4c9a548.png)

![image](https://user-images.githubusercontent.com/62531735/97513120-7702b680-19df-11eb-9438-493b72153be3.png)

**Comment by dawidd6** [comment]
But this `Layer via Docker` step is correctly run on failure as you can see.

**Comment by tb102122** [comment]
yes that is correct but the overall job fails due to the failure and the other matrix jobs are cancelled.

**Comment by dawidd6** [comment]
You can try `continue-on-error: true` set on the step level.

**Comment by tb102122** [comment]
you mean like this?

  - name: Layer via Artifacts
    continue-on-error: true
    if: (steps.git_diff.outputs.diff == false)
    uses: dawidd6/action-download-artifact@v2
    with:
      workflow: review.yml
      name: ${{ matrix.name }}
  - name: Layer via Docker
    if: steps.git_diff.outputs.diff && ${{ failure() }}
    id: layerD
    run: |

**Comment by dawidd6** [comment]
Yes

**Comment by tb102122** [comment]
no it does not work for some reason
![image](https://user-images.githubusercontent.com/62531735/97556709-ebfcdd00-1a2d-11eb-86ed-47e82aad5d46.png)

**Comment by tb102122** [comment]
sorry it worked my mistake. 
Now the step "   - name: Layer via Docker" is always running. 

      - name: Layer via Artifacts
        continue-on-error: true
        if: (steps.git_diff.outputs.diff == false)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: review.yml
          name: ${{ matrix.name }}
      - name: Layer via Docker
        if: steps.git_diff.outputs.diff || ${{ failure() }}
        id: layerD
        run: |

**Comment by tb102122** [comment]
Do you have any idea why the step is always running now?

**Comment by dawidd6** [comment]
Probably because of: `continue-on-error: true`

**Comment by tb102122** [comment]
no I am referring to the step "layer via Docker." 
the variable steps.git_diff.outputs.diff is false and failure() is also false but it is still executed.

**Comment by dawidd6** [comment]
Dunno. That's out of scope really for this issue.

**Comment by tb102122** [comment]
that resolved it

`  - name: Layer via Docker
    if: steps.git_diff.outputs.diff || failure()`
