### ISSUE TITLE
Feature request: use `workflow_status` with `branch`

### ISSUE THREAD

**Issue by jszwedko** [dawidd6/action-download-artifact#39]
It looks like using `workflow_conclusion` with `branch` (or `pr` or `commit`) is explicitly disallowed:

https://github.com/dawidd6/action-download-artifact/blob/f2f4c0c7333a76ab3aff16e7b2cf4ed7f5a74556/main.js#L26

But I'm not seeing why this needs to be the case.

It seems like it could be used as an additional filter with any of `branch`, `pr`, `commit`. It seems like it'd make less sense with `run_id` but practically it could still be used even with that option.

I can make a PR, but wanted to get validation on this first.

**Comment by dawidd6** [comment]
Please make a PR and we'll see.

**Comment by ipeshev** [comment]
Currently facing this problem, the only workaround is to split build workflow into two separate workflows. 
@dawidd6 any chance to get it soon ?
