### ISSUE TITLE
[Feature] Download from other repos

### ISSUE THREAD

**Issue by jpfeuffer** [dawidd6/action-download-artifact#4]
I wanted to ask if you think that it would in theory possible to extend this action to download
from workflows of other repos. In my case from the same organization. Or does that require another token/ some kind of authorization?

**Comment by dawidd6** [comment]
> The token's permissions are limited to the repository that contains your workflow.

https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret

It should be possible to implement this, but would require a token created by the user, rather the one provided by Actions (GITHUB_TOKEN).

**Comment by dawidd6** [comment]
Should be now possible by specifying `owner` and `repo` inputs.
