### ISSUE TITLE
Error: no artifacts found, but not on rerun

### ISSUE THREAD

**Issue by eirikstor** [dawidd6/action-download-artifact#42]
I have a workflow, which is triggered every night when a build server is finished and uploads several artifacts to github. 

My workflow tries to download one of these artifacts using the following job
<pre><code>jobs:
  download-image:
    runs-on: [self-hosted, magnus]
    steps:
      - name: Download workflow artifact ${{ github.event.inputs.image_name }}
        uses: dawidd6/action-download-artifact@v2.10.0
        with:
          workflow: ${{ env.SOURCE_WORKFLOW }}
          run_id: ${{ github.event.inputs.run_id }}
          name: ${{ github.event.inputs.image_name }}</code></pre>

The issue is that I get the `Error: no artifacts found` error during the night, but when I rerun the job / workflow later, it is successful. I've checked the timestamps on the uploading of the artifacts and confirmed that they are uploaded at least 1 hour before the download-image job has started. Any idea on how to fix this?

**Comment by dawidd6** [comment]
Sorry, but no.

**Comment by llicour** [comment]
I have sometime the same issue. I think this is something like a timing issue. This is not reproductible... I had to put a sleep step of 10s before starting downloading artifact. Perhaps a better way would be to manage a retry with a backoff...
