### ISSUE TITLE
Idea: Store downloaded files in a variable

### ISSUE THREAD

**Issue by hengi-comp** [dawidd6/action-download-artifact#44]
At the moment i check the downloaded files with an "ls" command.
It would be useful to output the downloaded files as a list in some output variable.
https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#outputs

**Comment by dawidd6** [comment]
Feel free to submit a PR for that.

**Comment by dawidd6** [comment]
I'm not gonna work on this. Please reopen the issue if you find yourself willing to return to this.
