### ISSUE TITLE
Unable to find remote repo (Error: Not Found)

### ISSUE THREAD

**Issue by rolyp** [dawidd6/action-download-artifact#45]
I’m trying to name the repo I want to download an artifact from. It’s a private repo, so I appreciate that I will need to provide appropriate credentials, but I’m actually getting an error which makes it look like it can’t parse the contents of the `repo` argument. What format should this be in?

| Argument | Message from Action | Error |
| ---- | ---- | ---- |
| `repo: https://github.com/user/repo/` | `==> Repo: https:/` | Error: Not found. |
| `repo: github.com/terrylyons/recombine/` | `==> Repo: github.com/terrylyons` | Error: Not Found |
| `repo: dawidd6/action-download-artifact` | `==> Repo: dawidd6/action-download-artifact` | Error: Not Found |

(Last example here was just to try it with a public repo which I know exists.)

I’m sure I’m missing something very obvious here, but I can’t figure out how to name in the repo in the `repo` argument.

**Comment by dawidd6** [comment]
Last row in the table is correct. `Error: Not Found` might indicate that there is no artifact with given name or other parameters.
