### ISSUE TITLE
Possibility to download last available artifact from a workflow

### ISSUE THREAD

**Issue by thebaptiste** [dawidd6/action-download-artifact#46]
Hello
In my workflow 1 uploading my artifact, when the workflow succeed, sometimes a new artifact is uploaded, sometimes not (depending on the result of a given step : if the artifact is unchanged, it is not uploaded in order to avoid to create useless artifacts and spare space).
So, in my workflow 2 downloading my artifact, I would like to download the "latest artifact of the given name uploaded by a successful run of worflow 1 **which produced an artifact**" (this will not always be the last successful run of worfklow1, because it may not have uploaded any artifact).
I don't think it is possible for the time being. I think it would be an interesting feature.

**Comment by dawidd6** [comment]
I think it should be possible by not specifying pr, commit, branch and run_id.

**Comment by thebaptiste** [comment]
Ok, great !
It didn't worked for me because : 
- I had specified "branch" (because I want to do that on a given branch, but as the branch name is in my artifact name, it is not necessary)
- I had specified "workflow_conclusion: success" which was probably bringing the run number of the last successful run
But without these two options it works.
You can close my issue.

Thank you for your action that significantly improves the basic actions/download-artifact !

Regards

**Comment by thebaptiste** [comment]
Sorry, I tried again, and it seems it doesn't work. It always try to download the artifact produced by the last run, and if this run did not produce an artifact, no artifact is downloaded.

**Comment by dawidd6** [comment]
Then I don't know.

**Comment by dawidd6** [comment]
Can you elaborate?

**Comment by dawidd6** [comment]
Need more info (workflow runs, workflow files) so I can debug it further. Nothing can be done currently as I don't know much.

**Comment by rodobarcaaa** [comment]
@dawidd6 I will try to explain more deeply.

In my case, every time I persist an artifact it is a release process that in turn publishes a staging, this artifact already carries the version number (**<<project_name>>-v1.0.0**), Obviously the version number and therefore the name of the artifact increases in each release process.

So when you publish to production it is another workflow that uses these artifacts ... and based on the version that you decide to publish, the download is requested, and this process is only working for the latest version and therefore it only downloads the artifact of the last workflow (release) executed.

We use it similar to this:

- make-release:
![image](https://user-images.githubusercontent.com/72995723/108497261-f287bc80-7289-11eb-8b13-77737d87ccbd.png)

- publish-production:
![image](https://user-images.githubusercontent.com/72995723/108497377-177c2f80-728a-11eb-9ee9-f12cd4bf0def.png)
![image](https://user-images.githubusercontent.com/72995723/108497615-7b065d00-728a-11eb-88ac-f97a1e061929.png)

I hope I have explained enough, however, if you need more, let me know.

Regards

**Comment by dawidd6** [comment]
Maybe specifying a commit would be helpful in your case? Still I would like to be able to browse the full repository and see how it works or not. Submitting a PR is an option too, if you can and verify that changes you made are indeed needed to make your workflow run as it should. Currently I'm not able to fully understand the issue.

**Comment by rodobarcaaa** [comment]
@dawidd6 I will try to make a public repo to share this case and be able to understand better.

**Comment by pjangam** [comment]
Seems like I'm facing a similar issue, I have 
```
 name: Download
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: stage.yml
          name: github_run_number
          path: github_run_number
          workflow_conclusion: success
```
This is how my download section looks like,

I'm getting an older file downloaded instead of from the last successful build

**Comment by dawidd6** [comment]
Did this issue emerged for you only recently (like yesterday)?

**Comment by pjangam** [comment]
Yes. Today in fact.

**Comment by dawidd6** [comment]
Then it's a GitHub API issue, see: https://github.com/dawidd6/action-download-artifact/issues/57

**Comment by pjangam** [comment]
Okay. Thank you. FYI, I'm not getting errors, but the GitHub action is downloading older artifact instead of latest.

**Comment by dawidd6** [comment]
Should be fixed now
