### ISSUE TITLE
PR number doesn't work

### ISSUE THREAD

**Issue by darianstlex** [dawidd6/action-download-artifact#75]
passing PR number to the action seems doesn't work, it doesn't appear in the logs, and always downloads the latest artefact from the given workflow from the latest run, so it takes it from the wrong PR:
<img width="407" alt="Screenshot 2021-05-20 at 12 18 37" src="https://user-images.githubusercontent.com/30862038/118970053-b4239b80-b965-11eb-9bbc-ba7fd182c105.png">
but I am passing it:
<img width="478" alt="Screenshot 2021-05-20 at 12 20 44" src="https://user-images.githubusercontent.com/30862038/118970163-d2899700-b965-11eb-9c0b-0700b0587ea4.png">

**Comment by darianstlex** [comment]
also, workflow is triggered from API using `repository_dispatch`.

**Comment by darianstlex** [comment]
ignore it :)

**Comment by sanex3339** [comment]
How did you fix it?

**Comment by darianstlex** [comment]
check my fork, as I remember it should work there
