### ISSUE TITLE
Getting latest artifacts when I want latest artifact based on branch name and event

### ISSUE THREAD

**Issue by SKuhlmanns** [dawidd6/action-download-artifact#77]
In my scenario I am trying to pull in artifacts from other projects (repo).  For example, we have a libraries repository and must pull in the correct artifacts as dependencies to a child project (repo), install them and build the application.  Some projects will pull artifacts from three different projects.  We attempting to handle this by making pull requests with the same user branch name and if the dependent project branch does not exist, we are attempting to use pull requests target branch.  In the pull_request.yml file I have:

      - name: Download Library artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.TOKEN}}
          # Required, workflow file name or ID
          workflow: pull_request.yml
          #workflow_conclusion: "completed,success"
          branch: sjk-LDV-648
          # Optional, will use specified workflow run
          #run_id: 1122334455
          #run_number: 34
          event: pull_request
          name: version-num-txt
          path: builder
          repo: SKuhlmanns/steves-test-repo

In SKuhlmanns/steves-test-repo
![image](https://user-images.githubusercontent.com/79860314/120670459-0c729700-c456-11eb-8453-5d6e9e7874a2.png)

I am expecting to get artifacts from pull request 59, but instead I am getting artifacts from pull request 60.  Maybe I don't understand how the action determines which workflow run to use when downloading artifacts?

**Comment by dawidd6** [comment]
Try specifying `pr` input instead of `branch`.

**Comment by SKuhlmanns** [comment]
Only the branch is known to the workflow.  It knows nothing about the pull request number or run id in the other project.  This is why am trying to use this action.  So, how do you search for the latest pr number or run id using the branch name (I am pretty new to github)?  For manual builds, this action works great, but I am trying to do continues builds, where projects are triggering other projects after being successfully built and where developers are making related changes in multiple projects and are expecting their changes to all build.

I have yet to find a way for one project to search another project for the correct artifacts based on branch name and workflow.  Originally, I was loading the successful builds run_id in an artifact called run_id-<branch_name>.txt and then searching for the latest run_id-<branch_name>.txt (using aochmann/actions-download-artifact@1.0.4); downloading the file, unzipping it, and using the run_id to pull the artifacts from the other project.  This was a work-around that I did not like,  I thought this action would be a better solution.

**Comment by SKuhlmanns** [comment]
Will using git hash work?  I maybe able to query the repository by branch name and get the git hash.

**Comment by dawidd6** [comment]
There is a `commit` input for that.

**Comment by SKuhlmanns** [comment]
I am in the process of trying to use:
            curl -sH "Accept: application/vnd.github.v3+json" \
            -u ${{ secrets.CURL_TOKEN }} -o curl_output.txt \
            https://api.github.com/repos/SKuhlmanns/steves-test-repo/branches/${{ github.base_ref }}
to query and get the branch information and then parse out the head git hash in curl_output.txt into a environment variable called " LIB_COMMIT_HASH" and using it in the action:
commit: ${{env.LIB_COMMIT_HASH}}

Am I complicating things or am I on the right track?

**Comment by dawidd6** [comment]
> I am expecting to get artifacts from pull request 59, but instead I am getting artifacts from pull request 60.

This seems odd. I would search for the issue here rather than creating some hacks. Something must be wrong with the branch name. Can't say what exactly, would need to dive deeper into this and I won't dedicate my time for that right now. Maybe try executing the Action locally with proper parameters and debug.

**Comment by SKuhlmanns** [comment]
I think the problem with using the branch name is that I have two or more branch names that are similar (for example ("sjk-LDV-648" and "sjk-LDV-648-2")  and I am specifically looking for artifacts for "sjk-LDV-648" and "sjk-LDV-648-2" is the last build; it gives me artifacts for "sjk-LDV-648-2".  Whereas a git hash is unique and will never find two matches.  I noticed that filtering from the github GUI on the workflow runs with "branch:sjk-LDV-648" gives me runs with branch names: "sjk-LDV-648-2", "sjk-LDV-648-2" and "sjk-release_v4.4-LDV-648" and "bugfix/sjk-release_v4.4-LDV-648", etc....  The GUI is searching/filtering based on *<branch_name>*.  Not sure this has anything to do with your action, but my solution above to use curl to search for the head git hash of the dependent repository branch is working as far as I can tell.  More testing will be needed.

Forgive me, but I am not a developer and know nothing about jscript.  My primary language development is bash and scripting languages.   I don't even know why the workflow file name is required in the action.  I assume it isolates runs to the named workflow and ignores the other runs.  I also assume that the repo: parameter forces the action to run on the named (target) repo instead of the calling (default) repo.   So, your comment about "... try executing the Action locally with proper parameters and debug" is over my head.  I would not know where to begin.  So, I usually implement things that I understand which seems like hacks to real developers.

You can close the ticket if you think this is more my problem than a problem with the action.  I appreciate your help.

**Comment by dawidd6** [comment]
Your observations about branch filtering in UI might be correct. I guess that's just how things work on GitHub's side. I don't see anything I could do here tho. Closing then.
