### ISSUE TITLE
ECONNREFUSED 

### ISSUE THREAD

**Issue by abelikt** [dawidd6/action-download-artifact#78]
Hi all, 
I'm having an issue with downloading artifacts that seems to be machine dependent.
It works fine on one machine but not on the other.
Both of them are Raspberry Pi's that are configured as self-hosted runners in github.

This is the log from GH Actions:

```
Run dawidd6/action-download-artifact@v2
==> Workflow: build-workflow.yml
==> Repo: abelikt/thin-edge.io
==> Conclusion: success
==> Branch: continuous_integration
Error: request to https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success failed, reason: connect ECONNREFUSED 140.82.121.6:443
```

It seems to work fine when I do this on the machine where it fails:
`curl "https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success"`

I'm quite puzzled.
Do you maybe have an Idea why this could happen?

Thanks & regards
Michael

**Comment by dawidd6** [comment]
Nope. For sure this is not the Action issue. More like octokit.js I would say, if curling the API works fine.

**Comment by abelikt** [comment]
Will open an issue here: https://github.com/actions/virtual-environments/issues
