### ISSUE TITLE
BUG: Failed to Generate URL to download artifact

### ISSUE THREAD

**Issue by mmcky** [dawidd6/action-download-artifact#82]
@dawidd6 -- this has been a super helpful `github action`. Thanks!

Just wondering if you have any ideas on how to fix this issue? Has the `github api` changed in the `url` structure?

<img width="513" alt="Screen Shot 2021-06-22 at 10 18 43 am" src="https://user-images.githubusercontent.com/8263752/122843634-3aefdd80-d343-11eb-97e7-6c7884c6569b.png">

Here is a github actions run:

https://github.com/QuantEcon/lecture-python.myst/pull/153/checks?check_run_id=2880290025

**Comment by dawidd6** [comment]
I see the next workflow run completed successfully:
https://github.com/QuantEcon/lecture-python.myst/runs/2880984500?check_suite_focus=true

Must have been a GitHub API hiccup. It happens.

**Comment by mmcky** [comment]
@dawidd6 I actually changed the structure of the workflows a little to have a separate `cache.yml` workflow rather than piggy backing on `publish.yml` to collect the `_build` folder which is working.

Maybe the `GithubAPI` has a time limit on files that isn't the same as the file retention policy?

**Comment by dawidd6** [comment]
Maybe maybe. Nothing we can do here I think.
