### ISSUE TITLE
GitHub token is not optional

### ISSUE THREAD

**Issue by oscarbenjamin** [dawidd6/action-download-artifact#92]
The README here says:
```
    # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
    github_token: ${{secrets.GITHUB_TOKEN}}, required if artifact is from a different repo
```
When I tried using this without the `github_token` I got:
```
Run dawidd6/action-download-artifact@v2
==> Workflow: test
==> Repo: oscarbenjamin/sympy
==> Conclusion: success
Error: Not Found
```
Adding in the `GITHUB_TOKEN` made it work so I guess that this is always required.

**Comment by oscarbenjamin** [comment]
To be clear I was attempting to access an artifact from the same repo.

**Comment by dawidd6** [comment]
Show me the repo

**Comment by oscarbenjamin** [comment]
Thanks. I must have gotten confused somewhere that that was the change that fixed it.
